# Generated by Django 5.2.4 on 2025-07-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('activo', 'Activo'), ('pasivo', 'Pasivo')], max_length=20, verbose_name='Tipo de Categoría')),
            ],
            options={
                'verbose_name': 'Categoría Contable',
                'verbose_name_plural': 'Categorías Contables',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Razón Social')),
                ('tipo_cliente', models.CharField(choices=[('individual', 'Persona Individual'), ('empresa', 'Empresa'), ('organizacion', 'Organización')], default='individual', max_length=20)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(default='OFICONT - Oficina Contable', max_length=200, verbose_name='Nombre de la Oficina')),
                ('direccion_oficina', models.TextField(default='Guatemala', verbose_name='Dirección de la Oficina')),
                ('telefono_oficina', models.CharField(default='', max_length=20, verbose_name='Teléfono de la Oficina')),
                ('email_oficina', models.EmailField(default='', max_length=254, verbose_name='Email de la Oficina')),
                ('moneda', models.CharField(default='Q', max_length=10, verbose_name='Moneda')),
                ('formato_fecha', models.CharField(default='DD/MM/YYYY', max_length=20, verbose_name='Formato de Fecha')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='ReporteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('balance_general', 'Balance General'), ('estado_resultados', 'Estado de Resultados'), ('flujo_efectivo', 'Flujo de Efectivo'), ('libro_diario', 'Libro Diario'), ('libro_mayor', 'Libro Mayor')], max_length=30, verbose_name='Tipo de Reporte')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo PDF')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente', verbose_name='Cliente')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte Contable',
                'verbose_name_plural': 'Reportes Contables',
                'ordering': ['-fecha_generado'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Tipo de Transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto (Q)')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_transaccion', models.DateField(verbose_name='Fecha de Transacción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoriacontable', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente', verbose_name='Cliente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
